export const INIT_MOVIES = "INIT_MOVIES";
export const INIT_MOVIES_SUCCESS = "INIT_MOVIES_SUCCESS";
export const INIT_MOVIES_FAIL = "INIT_MOVIES_FAIL";

export const SEARCH = "SEARCH";
export const SEARCH_SUCCESS = "SEARCH_SUCCESS";
export const SEARCH_FAIL = "SEARCH_FAIL";

export const AUTO_LOADING = "AUTO_LOADING";
export const AUTO_LOADING_SUCCESS = "AUTO_LOADING_SUCCESS";
export const AUTO_LOADING_FAIL = "AUTO_LOADING_FAIL";
